export const AppConfig = {
  site_name: 'Universe Unisex Store',
  locale: 'vi',
  title: 'Universe Unisex Store',
  description: 'Universe Unisex Store is the marketplace for the clothes, fashion of unisex...',
  keywords: 'Universe Unisex Store, Unisex, clothes,...',
  author: 'thuysddoox',
  website: 'https://bloodstockexchange.horse/',
  image: 'https://bloodstockexchange.horse/default.png',
  facebook: 'https://www.facebook.com/BloodstockEx',
  facebookName: 'Bloodstock Exchange',
  facebookUsername: 'BloodstockEx',
  twitter: 'https://twitter.com/bloodstockex',
  twitterName: 'Bloodstock Exchange',
  twitterUsername: 'bloodstockex',
  instagram: 'https://www.instagram.com/bloodstockexchange/',
  instagramUsername: 'bloodstockexchange',
};
